on:
  workflow_call: 
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        type: string
      checkout-ref:
        description: 'The commit SHA to checkout' 
        required: true
        type: string
    
jobs:
  push-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Lowercase Tag
        id: lowercase_tag
        run: |
          echo "repo_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "container_name=$(echo 'changelog.action' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          
      - name: Build and push Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: ./src/ChangeLogger.Action/Dockerfile
          push: true
          tags: ghcr.io/${{ env.repo_owner }}/${{ env.container_name }}:${{ inputs.version }}