on:
  push:

jobs: 
  test-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Update changelog
        uses: baynezy/ChangeLogger.Action@0.0.5.9
        with:
          tag: '1.0.0'
          repo-path: '/'
          log-path: './CHANGELOG.md'
          
      - name: Upload Changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: './CHANGELOG.md'